[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "howlongtobeatpy"
version = "1.0.18"
description = "A Python API for How Long to Beat"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.9"
authors = [
    { name = "ScrappyCocco" }
]
license = { text = "MIT" }
keywords = [
    "howlongtobeat", 
    "gaming", 
    "steam", 
    "uplay", 
    "origin", 
    "time", 
    "length", 
    "how long to beat"
]
dependencies = [
    "aiohttp>=3.11.10",
    "requests>=2.32.3",
    "aiounittest>=1.4.2",
    "fake_useragent>=2.0.3",
    "beautifulsoup4>=4.12.3"
]

[project.urls]
Homepage = "https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI"

[tool.setuptools]
zip-safe = false

[tool.setuptools.packages.find]
where = ["."]
include = ["howlongtobeatpy*"] 
exclude = ["tests"]